config:
  prefix: '&f[&cCoVID&f-&a19&f]'
  # In the world listed below, people wont get infected by mobs, sneezes or the infect command
  disabled worlds:
    - 'this_world'
    - 'that_world'
  # if true, infected players will not feel symptoms in disabled worlds
  symptoms disabled in disabled worlds: true
  infect command:
    # In case this was false this does not affect the console
    enabled: true
    # How many players is a player able to infect
    infected per player: 1
    # Radius needed for a player to infect another player with the infect command
    radius: 5
  # A medical mask for your players to protect themselves from other players and infected mobs
  mask:
    # permission for crafting the mask is 'corona.mask'
    enabled: true
    # in order to get a texture, you must put a players name and put it here https://freshcoal.com/index.php
    # it will give you a command like this:
    # /give @p skull 1 3 {display:{Name:"DarkHeroYT"},SkullOwner:{Id:"45ec0d88-898f-4ce8-9e5d-b28c75f79134",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjdhMDkwZDRjNmM5ZDUyODY2ZGNhNTY0Y2EwOTczOTg1YTY4OGJlYzg1YTNhMzA2Zjg1YjBhY2RiZDlhZGFiYSJ9fX0="}]}}}
    # get the eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjdhMDkwZDRjNmM5ZDUyODY2ZGNhNTY0Y2EwOTczOTg1YTY4OGJlYzg1YTNhMzA2Zjg1YjBhY2RiZDlhZGFiYSJ9fX0= from that and put it in here: https://www.base64decode.org/
    # the resulting URL is what you must put here
    texture URL: 'http://textures.minecraft.net/texture/8d85e4ef468311c653796807d418ef944b98a59155e24b0e1a42ec8c066074f'
    name: '&a&lMedical mask'
    lore:
      - '&fWith this mask you'
      - '&fcan protect yourself'
      - '&ffrom the virus'
    # Recipe is:
    # A B C #
    # D E F #
    # G H I #
    recipe:
      # Should the recipe be managed by this plugin
      enabled: true
      A: 'AIR'
      B: 'AIR'
      C: 'AIR'
      D: 'STRING'
      E: 'WHITE_WOOL'
      F: 'STRING'
      G: 'AIR'
      H: 'AIR'
      I: 'AIR'
  # A potion that players can drink to cure themselves from corona. It also gives absorption and weakness 5 for a minute
  cure potion:
    # The permission for crafting this potion is 'corona.curePotion'
    enabled: true
    name: '&cCure for &lcorona'
    lore:
      - '&fDrink this to cure'
      - '&fyourself from the &cvirus'
    # Recipe is:
    # A B C #
    # D E F #
    # G H I #
    recipe:
      # Should the recipe be managed by this plugin
      enabled: true
      A: 'GLASS'
      B: 'WITHER_ROSE'
      C: 'GLASS'
      D: 'GLASS'
      E: 'GOLDEN_APPLE'
      F: 'GLASS'
      G: 'GLASS'
      H: 'WATER_BUCKET'
      I: 'GLASS'
  # The sound played when an infected player feels a symptom
  sound:
    enabled: true
    sound: AMBIENT_CAVE
  # Cure command, also needs the 'corona.cure' permission
  cure:
    enabled: true
    price: 1000
  mobs that can infect:
    - ZOMBIE
    - SKELETON
    - WITHER_SKELETON
    - PHANTOM
  food that can infect:
    - COD
    - SALMON
    - MUTTON
    - TROPICAL_FISH
    - PUFFERFISH
    - DRIED_KELP
    - BEEF
    - CHICKEN
    - SPIDER_EYE
    - POISONOUS_POTATO
    - RABBIT
    - ROTTEN_FLESH
  # percentage of the chance a mob has to infect someone (out of 100)
  chance to infect:
    mob:
      without mask: 10
      with mask: 2
    food: 20
  messages:
    no permission: '&cNo permission'
    reloaded: '&aPlugin reloaded!'
    unknown command: '&cUnknown command. Run &e/%command% help &cto see a list of commands'
    disabled: '&cThat command is disabled!'
    world disabled: '&cThat feature is disabled in this world'
    not online: '&cThat player does not exist or is not online'
    given mask: '&aJust gave %player% a &lmask'
    received mask: '&a%player% just sent you a &lMask&a. stay home!'
    self received mask: '&aReceived &lMask'
    full inv: '&c%player%s inventory is full'
    mask disabled: '&cThe &amedical mask &cis disabled in config, please enable it in order to get it'
    console mask: '&cThe console is already protected from coronavirus, it does not need a mask &f(try /corona givemask (player))'
    you are not infected: '&cYou are not infected so you cannot infect anyone else'
    now infected: '&f&lYou are now infected with &4CoVID&f-&a19 &f&lbeware of any symptoms'
    feeling symptoms: '&cYou are feeling %symptom% because of coronavirus'
    just infected someone: '&f%infecter% just infected %infected% with CoVID&f-&a19'
    too many infected: '&cYou have infected as many people as you could'
    must be in radius: '&cYou are too far from that player. you must be less than %radius% blocks apart'
    already infected: '&cThat player is already infected'
    cure disabled: '&cThe cure has not been found yet'
    not enough money: '&cYou do not have enough money, you need: &f%price%'
    not infected: '&cThat player is not infected'
    cured someone: '&aYou just cured &f%cured%'
    cured you: '&f%curer% &ajust cured you'
    has cured: '&f%curer% &ahas cured &f%cured%'
    player not infected: '&cThat player is not infected'
    sneezed: '&c%player% just sneezed'
    you sneezed: '&cYou just sneezed! Bless you'
    cannot place: '&cHey, if i were you i would put that on my head instead of the floor'
    cure command disabled: '&cEconomy is disabled, therefore the cure command is also disabled'
    cured by potion: '&aA magic &5&lelixir &ajust cured you from the virus!'
    someone cured by potion: '&aA magic &5&lelixir &ahas cured &l%player% &afrom the virus!'
    cannot use potion: '&cYou are not infected, give that potion to someone that needs it better!'
    potion disabled: '&cThe &5potion &cis disabled in config.'
    console potion: '&cThe console is already protected from coronavirus, it does not need a cure &f(try /corona givePotion (player))'
    self received potion: '&aReceived &5potion'
    given potion: '&aJust gave %player% a &5potion'
    received potion: '&a%player% just sent you a &5potion&a. stay home!'
    check:
      self: '&fYou are %infected%'
      others: '&f%player% is %infected%'
    check infected: '&cInfected'
    check not infected: '&aHealthy'
    console cannot get infected: '&cThe console cannot get infected'
  infected:
    random sneezes:
      # Should random infected players sneeze and have the possibility to infect others by doing so?
      enabled: true
      # Operation mode for random sneezes: "all": every infected player will sneeze. "random": Only one random infected player will sneeze
      mode: all
      # Interval between sneezes, specify "s" for seconds, "m" for minutes and "h" for hours
      interval: 10m
      # Any player in this radius has probability to get infected
      radius: 5
      # This is the probability someone that sneezes has to infect a healthy player without mask
      probability to infect: 80
      # How players with masks should react to sneezes (100%: not affected by sneezes. 0%: will get infected when someone sneezes near them)
      # Also, the probability for infecteds not to infect someone by sneezing
      # (They do not add up)
      mask effectiveness: 90
      # Sound played when a player sneezes, to himself and the surrounding (not infected) players
      sound:
        enabled: true
        params:
          sound: ENTITY_GHAST_HURT
          pitch: 1.0
          volume: 0.5
    # How long it takes a player to feel a symptom, specify "s" for seconds, "m" for minutes and "h" for hours
    interval: 2m
    # Effect,duration in seconds, amplifier
    symptoms:
      - CONFUSION,10,2
      - POISON,10,1
      - WEAKNESS,20,1
      - BLINDNESS,5,1